<script lang="ts">
  import BasicContentArea from '$lib/components/basic-content-area.svelte';
  import IntroBox from '$lib/components/intro-box.svelte';
  import Section from '$lib/components/section.svelte';
  import Stage from '$lib/components/stage.svelte';
  import { m } from '$lib/paraglide/messages';
  import { localizeHref } from '$lib/paraglide/runtime';
</script>

<svelte:head>
  <title>{m['topics.ras.dataManagement.title']()}</title>
  <meta name="description" content={m['topics.ras.dataManagement.title']()} />
</svelte:head>

<Stage>
  <IntroBox title={m['navigation.topics.dataManagement']()} description={m['aboutUs.introDescription']()}></IntroBox>
</Stage>

{#snippet left()}
  <div class="prose">
    <h1>{m['navigation.topics.dataManagement']()}</h1>
    <h3>Competency</h3>
    <p>
      Using standard-technology for business intelligence solutions STRATECO closes this gap by trans-forming Output data from various Kamakura Risk Manager
      (KRM)* source tables into a data-warehouse accessed by state of the art OLAP (online analytical processing) technology. End-users are then able to explore
      data generated by KRM’s algorithms using Excel or by browsing through pre-defined web-based reports. Utilizing such data-warehouse technology subsequent
      analysis- and reporting efforts will become more efficient. Compared with using relational database systems, adoptions will take less time and will be
      less costly.<br />
    </p>
    <h3>Main Focus</h3>
    <ul>
      <li>Explore data intuitively using Excel Pivot and via web service</li>
      <li>High performance independent of the amount of underlying source data</li>
      <li>Historization of KRM output data allows comparisons of results over time</li>
      <li>Built in ability to drilldown across multiple dimensions</li>
      <li>Flexible definition of access rights / Easily integrates into existing IT environment</li>
      <li>Standard technology (MS Office, MS SQL Server, Oracle)</li>
    </ul>
    <h3>Solutions</h3>
    <p>STRATECO OLAP Solution for KRM*</p>
    <p>
      <strong>*KRM</strong><br /> Kamakura Risk Manager (KRM) is a state-of-the-art fully integrated enterprise risk management system. Though being the only company
      to provide fully integrated risk solutions based on common assumptions And methodologies, it has a major weakness in providing helpful tools to analyze and
      report on the current And future financial risk positions its engine is able to project. Therefore both analysis as well as Subsequent reporting, appear as
      bottlenecks on projects dealing with KRM.
    </p>
    <h3>Branchen</h3>
    <ul>
      <li><a title="Financial Institutions " href="/Kompetenzen/Financial-Institutions">Financial Institutions</a></li>
      <li><a title="Healthcare" href="/Kompetenzen/Pharma-Healthcare">Healthcare</a></li>
      <li><a title="Telecoms, Media, High Tech" href="/Kompetenzen/Telecoms-Media-High-Tech">Telecoms, Media, High Tech</a></li>
      <li><a title="Travel, Transport &amp; Logistics" href="/Kompetenzen/Travel-Transport-Logistics">Travel, Transport &amp; Logistics</a><br /></li>
      <li><a title="Sonstige" href="/Kompetenzen/Sonstige">Sonstige</a></li>
    </ul>
  </div>

  <a href={localizeHref('/topics/ras')}>Zurück zu Übersicht</a>
{/snippet}
{#snippet right()}{/snippet}
<Section>
  <BasicContentArea {left} {right} />
</Section>
